name: Web Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 68f9bf7a63a9b5125c7e65c51ff9a2d4
          projectName: infinitydoc-web
          directory: public
          branch: main
          wranglerVersion: "3"
